# Generated by Django 2.1.8 on 2019-08-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triphub_Room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=200)),
                ('order', models.CharField(max_length=20)),
                ('attraction', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='myroom',
            name='attractions',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myroom',
            name='city',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myroom',
            name='ispass',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memberlist',
            name='room_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='memberlist',
            name='user_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='myroom',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='myroom',
            name='room_id',
            field=models.CharField(max_length=200),
        ),
    ]
